exp_name="ace"

# python main.py --exp_name $exp_name --mode "preprocess"
# python main.py --exp_name $exp_name --mode "merge"
CUDA_VISIBLE_DEVICES=0 python main.py --exp_name $exp_name --mode "train"
# CUDA_VISIBLE_DEVICES=0 python main.py --exp_name $exp_name --mode "evaluate" --sub_mode "final-fixed519-multi-selectors"
# python main.py --exp_name $exp_name --mode "statistic"
# python main.py --exp_name $exp_name --mode "indicator" --sub_mode "dev"
# python main.py --exp_name $exp_name --mode "rank" --sub_mode "dev-scale"
# python main.py --exp_name $exp_name --mode "save" --sub_mode "best_1200-fixed519-lr1e-3"
# CUDA_VISIBLE_DEVICES=0 python main.py --exp_name $exp_name --mode "meta"
# CUDA_VISIBLE_DEVICES=0 python main.py --exp_name $exp_name --mode "threshold"
# python main.py --exp_name $exp_name --mode "group"