exp_name="ace_meta2"

CUDA_VISIBLE_DEVICES=3 python main.py --exp_name $exp_name --mode "train"
# CUDA_VISIBLE_DEVICES=3 python main.py --exp_name $exp_name --mode "evaluate" --sub_mode "final-fixed519-multi-selectors"
# CUDA_VISIBLE_DEVICES=3 python main.py --exp_name $exp_name --mode "meta"
# python main.py --exp_name $exp_name --mode "save" --sub_mode "best-fixed519-lr5e-4"
# CUDA_VISIBLE_DEVICES=3 python main.py --exp_name $exp_name --mode "indicator" --sub_mode "best-seed512"
# python main.py --exp_name $exp_name --mode "rank" --sub_mode "best-seed512-False"
# CUDA_VISIBLE_DEVICES=3 python main.py --exp_name $exp_name --mode "P-R" --sub_mode "best-meta"
# CUDA_VISIBLE_DEVICES=3 python main.py --exp_name $exp_name --mode "number"